global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'ptsecurity'
    static_configs:
      - targets: ['https://ptsecurity.com']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        regex: 'https://ptsecurity.com'
        replacement: 'ptsecurity'
        target_label: instance

  - job_name: 'blackbox'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://ptsecurity.com
    relabel_configs:
      - source_labels: [__address__]
        regex: 'https://ptsecurity.com'
        replacement: 'ptsecurity'
        target_label: instance